const float TANK_LABEL_START_POS_X = FIELD_WIDTH + 100;
const float TANK_LABEL_START_POS_Y = FIELD_OFFSET_Y; 

const float LIVE_LABEL_START_POS_X = TANK_LABEL_START_POS_X + 100; 
const float LIVE_LABEL_START_POS_Y = TANK_LABEL_START_POS_Y;
const float LIVE_LABEL_WIDTH = BARRIER_WIDTH * 6;
const float LIVE_LABEL_HEIGHT = BARRIER_HEIGHT * 4;